pipeline {
    agent any
    tools { 
      maven 'Maven3.8.6'
    }
    stages {
        stage('github clone') {
            steps {
                git branch: 'master', url: 'https://github.com/kang-jaehoon/web-cicd.git'; 
            }
        }
        
        stage('build') {
            steps {
                sh '''
                    echo build start
                    mvn clean compile package -DskipTests=true
                '''
            }
        }
        
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarQube-server') {
                    sh 'mvn sonar:sonar'
                }
            }
        }
    }    
}